from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import Optional, Any
import json

from app.schemas.job import JobCreate
from app.core.database import get_db
from app.models.infographic import Infographic
from app.models.user import User
from app.api.deps import get_current_user
from app.services.ai_service import generate_structured_content

router = APIRouter()

@router.post("/generate", status_code=200)
async def generate_infographic(
    job_in: JobCreate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Submits a new infographic generation topic. Returns structured JSON immediately.
    """
    if current_user.usage_count >= current_user.limit_month:
        raise HTTPException(
            status_code=403, 
            detail=f"Usage limit exceeded. Please upgrade your tier. Current usage: {current_user.usage_count}/{current_user.limit_month}"
        )

    try:
        # Generate JSON content
        infographic_data = await generate_structured_content(job_in.topic)
        
        # Save to DB
        new_info = Infographic(
            user_id=current_user.id,
            topic=job_in.topic,
            data=json.dumps(infographic_data)
        )
        db.add(new_info)
        
        # Increment usage
        current_user.usage_count += 1
        
        await db.commit()
        await db.refresh(new_info)
        
        return infographic_data

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/gallery")
async def get_user_gallery(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Retrieve all infographics generated by the user.
    """
    result = await db.execute(
        select(Infographic).where(Infographic.user_id == current_user.id).order_by(Infographic.created_at.desc())
    )
    infographics = result.scalars().all()
    
    # parse json data 
    res = []
    for info in infographics:
        res.append({
            "id": info.id,
            "topic": info.topic,
            "created_at": info.created_at,
            "data": json.loads(info.data)
        })
    return res

